version: 2

updates:
  # Dépendances Node.js
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"

    open-pull-requests-limit: 5

    groups:
      npm-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "Europe/Paris"

    groups:
      github-actions:
        patterns:
          - "*"

  # Image Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Paris"